on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * 1-5'

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  SLACK_CHANNEL_IDS: ${{ secrets.SLACK_CHANNEL_IDS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
          pip install openai
          pip install slack-sdk

      - name: run SlackGPT
        run: |
          python slackgpt.py
